name = "UnfoldDRE"
uuid = "936392d6-56ff-4756-a116-4ff861f79fbe"
authors = ["Anmol Jain", "Benedikt Ehinger"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
